name: flutterlifecyclehooks
description: A flutter package that let you easily add hooks for application lifecycle state
version: 3.0.1
homepage: https://github.com/spideythewebhead/flutterlifecyclehooks

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  flutter_lints: 2.0.1

flutter:
